### ISSUE TITLE
Error when running Fusion/TMS2Independent example

### ISSUE THREAD

**Issue by cwenger** [thermofisherlsms/meth-modifications#26]
I am getting an error when I try to run the [Fusion/TMS2Independent example](https://github.com/thermofisherlsms/meth-modifications/tree/master/examples/Fusion/TMS2Independent). The full error with stack trace is:

```
xmlmethodchanger\bin\Release\XmlMethodChanger.exe -i examples\Fusion\TMS2Independent\TMS2IndependentTemplate.meth -m examples\Fusion\TMS2Independent\TMS2Independent.xml -o examples\Fusion\TMS2Independent\TMS2Independent.meth

template: examples\Fusion\TMS2Independent\TMS2IndependentTemplate.meth xml: examples\Fusion\TMS2Independent\TMS2Independent.xml output: examples\Fusion\TMS2Independent\TMS2Independent.meth model:  version:
model: OrbitrapFusion version:
ERROR - Error Importing Update Instructions XML
ExceptionSystem.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at Thermo.TNG.Calcium.MethodXML.ModificationsImporter.HandleActivationParams(TMSnScan tMSNScan, CalciumTMSnScan mScan)
   at Thermo.TNG.Calcium.MethodXML.ModificationsImporter.ApplyModification(CalciumMethod method, Int32 index, TMSnScan tMSNScan, String label, Boolean requireModification)
   at Thermo.TNG.Calcium.MethodXML.ModificationsImporter.ApplyModification(CalciumMethod method, Experiment expModification, Int32 expIndex, CalciumExperiment experiment, String targetLabel, Boolean requireModification)
   at Thermo.TNG.Calcium.MethodXML.ModificationsImporter.ApplyModification(CalciumMethod method, Experiment exp)
   at Thermo.TNG.Calcium.MethodXML.ModificationsImporter.ApplyModification(CalciumMethod method, Modification mod)
   at Thermo.TNG.Calcium.MethodXML.ModificationsImporter.<>c__DisplayClass0_0.<Import>b__0(Modification o)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Thermo.TNG.Calcium.MethodXML.ModificationsImporter.Import(CalciumMethod method, MethodModifications data)
   at Thermo.TNG.Calcium.MethodXML.CalciumMethodXML.ApplyMethodModifications(MethodModifications data)
   at Thermo.TNG.Common.Method.MethodXML`2.ApplyMethodModificationsFromXML(String xmlData)
```

The [Fusion/TMS2Dependent example](https://github.com/thermofisherlsms/meth-modifications/tree/master/examples/Fusion/TMS2Dependent) works, while the [Fusion/DIA example](https://github.com/thermofisherlsms/meth-modifications/tree/master/examples/Fusion/DIA) also fails, so it seems to be related to `TMSnScan` nodes.

**Comment by jesse-canterbury** [comment]
Sorry for the delay on this.  It's on our radar.
